Repository Pawcio1235/props_pp, pull requests merged in 2024-04, with the labels that each got.

#1 chore: add task
  README.md
Labels: documentation

#2 add print name
  main.py
Labels: enhancement

#3 merge on print
  README.md
  main.py
Labels: documentation, enhancement
